### ISSUE TITLE
Unexpected pixelbuffer getter

### ISSUE THREAD

**Issue by Yasuhisa** [Yasuhisa/SearchByImage#3]
## Overview
Pixelbuffer getter returns unexpected value.

## TODO
- [x] fix pixelbuffer getter
- [x] get pixelbuffer correctly
- [x] handle pixelbuffer correctly

## Relations
- fda41990ef565953ef3b1f5dfb6c1e4f38497f98

**Comment by Yasuhisa** [comment]
fixed this issue.
